[project]
name = "headlines"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["core"]

[tool.uv.sources]
core = {workspace = true}

[tool.uv.workspace]
members = [ "packages/*" ]
